### ISSUE TITLE
Site Name - Login

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#110]
The change in position of the site name on the login screen results in the site name not being present at all on the login screen on mobile.

### Main Repo
![image](https://user-images.githubusercontent.com/1296369/55667875-12f72b00-585a-11e9-9f96-018e1f7be7d5.png)

### This Repo
![image](https://user-images.githubusercontent.com/1296369/55667870-ff4bc480-5859-11e9-8999-1c8f364c427d.png)

**Comment by brianteeman** [comment]
Correction - I discovered by accident that it is there if you were to scroll down - I do not understand why the site name is not at the top

![correction](https://user-images.githubusercontent.com/1296369/55667906-65d0e280-585a-11e9-9b2b-2fcd6191543a.gif)

**Comment by coolcat-creations** [comment]
Maybe let's repeat the sitename next to the Joomla icon at the top?

**Comment by brianteeman** [comment]
Better yet - put it back where it was - instead of duplicating it

**Comment by zwiastunsw** [comment]
Why do you necessarily want to include the title of the page and the name of the site on this screen? 
Of course, you can do this. 
Question: What for? 
The sighted user  recognizes by the appearance whether he or she has found the page to which he or she wants to log in. For a blind user this information is annotated by the screen reader from the "title" attribute. 
If you want to add a website name, add it in the page header - because this is the right place for page identification data.

**Comment by brianteeman** [comment]
The sighted user does NOT know if they are on the correct page if they have multiple tabs open with multiple sites all showing the admin login screen

**Comment by zwiastunsw** [comment]
It's hard to deny you the truth. But...
I am a sighted user. I sometimes have 10 websites and more open in my browser. Believe me. I know them easily, not because I read the name of the site, which in Joomla 3 is displayed to me in the lower right corner of the screen, in a place I rarely look at. I recognize the necessary website by its address in the address bar of my browser.
However, I don't open 20 sites on my mobile phone. I open one website. And here I also see the address bar.

**Comment by coolcat-creations** [comment]
Please don't discuss on this level. We will improve the recognition of the sitetitle on mobile, people work differently with joomla we need to take care of differences. We can't cover everything but we can do the easy ones. Unless we have an UX Epert somewhere around, we have to do just whatever is possible.

We will make Joomla great if we work together as good as possible and not if we use Uppercases and sublimal messages. Please be nice to each other on a work level. Lets put the energy into Joomla, ok?

Thank you for your valueable work and comments.

> It's hard to deny you the truth. But...

> The sighted user does NOT

**Comment by zwiastunsw** [comment]
> Please don't discuss on this level. 

I give only my opinion. I do not judge or deny absolutely different views. Remember that my English language is weak.  I try my best to present my opinion. And that's all.

**Comment by coolcat-creations** [comment]
Closed as we have a commit to show the sitename in topbar 2f2c5867d192ec8f26d0e70eaecb0d1c4100a9d7
