### ISSUE TITLE
Sidebar - joomla logo

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#120]
In previous iterations of the sidebar the joomla branding was fixed to the bottom of the sidebar. Now it is just floating below the menu so moves when the menu expands etc.

I was always taught that branding should be consistent and that included its positioning

**Comment by coolcat-creations** [comment]
Well from design and marketing perspektive things changed over the years. Logos can move, animate, change, be cut off ... It depends on the brand guidelines or the creatives behind. In this case the logo was a problem for the general overview and orientation for the user. A disruption. We removed the logo from there anyway because it's already twice in the top bar. One can be changed to a custom logo but the version logo will always stay in the top bar and give brand recognition. Closing due to this.
