### ISSUE TITLE
Post-installation messages

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#123]
![image](https://user-images.githubusercontent.com/1296369/55720513-ef1e1b80-59f8-11e9-9b7c-47e30b04a32f.png)

As discussed before it is a really bad idea to both truncate the message and to allow it to be dismissed here.

The entire point of the messages is to make sure that people read them

**Comment by coolcat-creations** [comment]
@lavipr @fancyFranci can you remove the dismiss icons and add a "Visit messages page" Link at the bottom ? - Wording can be changed, I don't know how to name the link, maybe @brianteeman you have an idea.

**Comment by brianteeman** [comment]
why add the link - the messages are already links

**Comment by coolcat-creations** [comment]
Actually... I wonder if we need the dropdown then at all or just link to the page...

**Comment by brianteeman** [comment]
What was the problem you were trying to solve

**Comment by coolcat-creations** [comment]
I'd prefer to close the message right in the Dropdown - because actually I am always quite annoyed that I have to dismiss the stuff over and over again in each installation, If there is a discussion going on that this is not good practise I wonder if we need to show the messages in the dropdown at all.

**Comment by brianteeman** [comment]
We discussed this previously. We have to make changes for the benefit of everyone not ourselves just because we can. It's actually less clicks for you to go to the component and press hide all messages than to dismiss them one at a time without reading them.

**Comment by coolcat-creations** [comment]
"If there is a discussion going on that this is not good practise I wonder if we need to show the messages in the dropdown at all." 

... Which I said in my message. I am always open for improvements.

> We have to make changes for the benefit of everyone not ourselves just because we can.

For now, as we have no UX Expert in Joomla its always a bunch of individual opinions, because there are no statistics, no user researches, no user test.

**Comment by coolcat-creations** [comment]
Closing since closing buttons are removed #136 #137
